packages/packages.json, packages/valory/services/mech/service.yaml
Fixes the api keys' override on the service spec.
=> Fix api keys' override on the service spec

.example.env, packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/connections/websocket_client/connection.py, packages/valory/connections/websocket_client/connection.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/contract_subscription/behaviours.py, packages/valory/skills/contract_subscription/handlers.py, packages/valory/skills/contract_subscription/skill.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution_abci/behaviours.py, packages/valory/skills/task_execution_abci/models.py, packages/valory/skills/task_execution_abci/skill.yaml
Performs various fixes in configs, connection, missed parts, file hash to tools loading, and editing params, which is forbidden.
=> Various fixes

.example.env, packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution_abci/skill.yaml
Updates IPFS hash for the tools to the latest.
=> Update IPFS hash

.example.env
=> fix: example.env

README.md
- Update .olas links.
- Clarified a few points in README.md
=> Update .olas links

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution_abci/behaviours.py, packages/valory/skills/task_execution_abci/skill.yaml
This PR allows for tools to fail processing requests by marking those requests as invalid.
=> fix: allow for failures in tools

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/contracts/agent_registry/__init__.py, packages/valory/contracts/agent_registry/build/AgentRegistry.json, packages/valory/contracts/agent_registry/contract.py, packages/valory/contracts/agent_registry/contract.yaml, packages/valory/contracts/agent_registry/tests/__init__.py, packages/valory/contracts/agent_registry/tests/test_contract.py, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_submission_abci/behaviours.py, packages/valory/skills/task_submission_abci/models.py, packages/valory/skills/task_submission_abci/skill.yaml, poetry.lock, pyproject.toml, tox.ini
This PR adds support for updating the agent hash on-chain.
=> feat: add ability to update the agent hash on-chain

tools/prediction_request_embedding/component.yaml
This PR fixes the entrypoint for `prediction_sentence_embedding` tool.
=> chore: fix entrypoint

docs/index.md
=> Add missing docs sections

tools/prediction_request/prediction_request.py, tools/prediction_request_sme/prediction_request_sme.py
Affects people calculating usage costs (e.g. on the benchmark)
=> fix bug in tools

tools/resolve_market/__init__.py, tools/resolve_market/component.yaml, tools/resolve_market/resolve_market.py, tools/resolve_market_reasoning/__init__.py, tools/resolve_market_reasoning/component.yaml, tools/resolve_market_reasoning/resolve_market_reasoning.py
Add resolve market tools
```
Processing package: /mech/tools/resolve_market
Added: `resolve_market`, hash is bafybeib57pk53zbrvwkmgmanj2kwyeu4o3jz2bof2inad6xzzd6bwycukq
Processing package: /mech/tools/resolve_market_reasoning
Added: `resolve_market_reasoning`, hash is bafybeigvcb2xomrem3nsmfvnygq3o4hz3mlcm6tso4lziql4nrrd4umzpe
```
=> Add resolve market tools

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/task_execution/behaviours.py, packages/valory/skills/task_execution/skill.yaml
This PR adds support for handling the timeout of tasks.
=> fix: add handling for timed-out tasks

packages/napthaai/customs/prediction_request_rag/component.yaml, packages/napthaai/customs/prediction_request_rag/prediction_request_rag.py, packages/packages.json
this fixes errors encountered in mech over the last week.
=> fix prediction-request-rag

packages/napthaai/customs/resolve_market_reasoning/component.yaml, packages/napthaai/customs/resolve_market_reasoning/resolve_market_reasoning.py, packages/packages.json
Hot fix to change the response type of `resolve_market_reasoning`.
=> fix: response type on resolve_market_reasoning.py

packages/napthaai/customs/resolve_market_reasoning/component.yaml, packages/napthaai/customs/resolve_market_reasoning/resolve_market_reasoning.py, packages/packages.json
This PR fixes the response for the `transaction` on the response on the `resolve_market_reasoning` tool.
=> fix: transaction response on `resolve_market_reasoning.py`

README.md
=> Improve interface doc & fixes

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/task_execution/behaviours.py, packages/valory/skills/task_execution/skill.yaml
This PR adds metadata to the IPFS response.
=> feat: add metadata to ipfs response

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_execution/utils/benchmarks.py, poetry.lock
- added claude models to the token counter
=> add claude models to token counter

packages/packages.json
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> Remove redundant package

poetry.lock, pyproject.toml
`tomte` doesn't need to be a core dependency of this repo. Move it to a dev dependency to avoid unnecessary dependency restrictions on dependant projects.
=> Make tomte a dev dependency

README.md
Adds info about the deps on tools.
=> Add tool deps README.md

packages/napthaai/customs/resolve_market_reasoning/component.yaml, packages/packages.json
Adds default model to `resolve_market_reasoning`.
=> fix: add default model to `resolve_market_reasoning`

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/contracts/agent_mech/contract.py, packages/valory/contracts/agent_mech/contract.yaml, packages/valory/contracts/balance_tracker/__init__.py, packages/valory/contracts/balance_tracker/build/BalanceTracker.json, packages/valory/contracts/balance_tracker/contract.py, packages/valory/contracts/balance_tracker/contract.yaml, packages/valory/contracts/mech_marketplace/contract.py, packages/valory/contracts/mech_marketplace/contract.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/subscription_abci/skill.yaml, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_submission_abci/behaviours.py, packages/valory/skills/task_submission_abci/skill.yaml, tox.ini
Adds a process payment which transfers the funds from balance tracker to mech before the profit split algorithm
=> adds process payment for mech

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution/behaviours.py, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_submission_abci/skill.yaml, tox.ini
Fixes the following issue which causes the mech to crash
```
executing_task["requestId"],
2025-05-14 20:16:46.756	2025-05-14T20:16:46.562051961Z stdout F     ~~~~~~~~~~~~~~^^^^^^^^^^^^^
2025-05-14 20:16:46.756	2025-05-14T20:16:46.562066331Z stdout F TypeError: 'NoneType' object is not subscriptable
```
=> fixed mech crashing if executing task is not present

README.md, packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution/behaviours.py, packages/valory/skills/task_execution/handlers.py, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_submission_abci/behaviours.py, packages/valory/skills/task_submission_abci/skill.yaml
- Add `self._last_deadline = None`  in `def _execute_task(self)`
- Remove the recursion at the end of the if in `def _execute_task(self)`
- Call `self._handle_timeout_task()`
- Reorganised max retry logic inside `_handle_timeout_task` for better readability
Successfully, reset the `last_deadline` and `async_result`
Provides a fix for out of sync mechs. 
Linear task: https://linear.app/valory-xyz/issue/LAU-167
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
=> Out of sync fix.

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_execution/utils/benchmarks.py, packages/valory/skills/task_submission_abci/skill.yaml
We are going to introduce a new model in the prediction tools so we need the corresponding cost information for this model.
It brings a new feature (no cost info for Claude 4)
- [X ] Non-breaking feature (non-breaking change which adds functionality)
- [X ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ X] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> Add cost configuration for Claude 4 model

tox.ini
fixes liccheck ci failture on main
=> fix: liccheck

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution/handlers.py, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_submission_abci/skill.yaml
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
Fix an issue where priorityMech would be capitalised and we compaire with lower case address, that made the mech to always ignore its own requests.
=> Fix comparison between addresses

packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_execution/handlers.py, packages/valory/skills/task_execution/skill.yaml, packages/valory/skills/task_submission_abci/skill.yaml
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> fix: logging

.github/workflows/common_checks.yaml, README.md, packages/packages.json, packages/valory/agents/mech/aea-config.yaml, packages/valory/services/mech/service.yaml, packages/valory/skills/mech_abci/skill.yaml, packages/valory/skills/task_submission_abci/behaviours.py, packages/valory/skills/task_submission_abci/models.py, packages/valory/skills/task_submission_abci/skill.yaml, tox.ini
Adds default value for nvm deliveries if tool to pricing is not available 
If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> sets default value for nvm deliveries
